### ISSUE TITLE
move repo into refinery-platform organization

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#1504]
Update deployment, testing, and webhooks: https://github.com/parklab/refinery-platform/search?utf8=✓&q=parklab.

Make sure that github-pages are still working.

How would this affect SCC deployments on AWS, local dev environments, wiki links, readme, refinery-platform.org site, etc

**Comment by scottx611x** [comment]
### About repository transfers:
https://help.github.com/articles/about-repository-transfers/#whats-transferred-with-a-repository

**Notable takeaways:**

- `"If the transferred repository contains a GitHub Pages site, then links to the Git repository on the Web and through Git activity are redirected. However, we don't redirect GitHub Pages associated with the repository."`
- `"If the transferred repository contains webhooks, services, or deploy keys, they will remain associated after the transfer is complete."`
- `"All Git information about commits, including contributions, are preserved, unless Git history has been rewritten using git rebase"`
- `"When the current owner initiates the transfer, the new owner will receive an email giving the option to accept or reject the transfer. If the new owner doesn't accept the transfer within one day, it won't complete."`
- `"To avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL."`

**To-Dos**:
- [ ] Update references to https://github.com/parklab/refinery-platform in codebase
- [ ] Transfer ownership to refinery-platform org.
- [ ] Everyone should run: git remote set-url origin https://github.com/refinery-platform/refinery-platform

**Comment by hackdna** [comment]
Thanks. What about existing SCC deployments on AWS, Github wiki, refinery-platform.org site? Any other impacts you can think of?

**Comment by hackdna** [comment]
Also, shouldn't the URL for the new origin be `git@github.com:refinery-platform/refinery-platform.git`?

**Comment by scottx611x** [comment]
@hackdna Yes that should be the URL.

- Wiki links should be taken care of per:
`"All links to the previous repository location are automatically redirected to the new location."`

- Existing AWS deploys should also run:
`git remote set-url origin git@github.com:refinery-platform/refinery-platform.git` 
after the repo transfer is complete

- Travis *should* just work (the current env vars for SauceLabs may need to be re-added)

- For the Github Pages site: "If the transferred repository contains a GitHub Pages site, then links to the Git repository on the Web and through Git activity are redirected. However, we don't redirect GitHub Pages associated with the repository."

**Comment by scottx611x** [comment]
https://blog.kevin-brown.com/github/2015/01/15/transferring-repositories-cleanly-on-github.html

**Comment by scottx611x** [comment]
Closing as all foreseen outcomes have been tested and are working properly.

We can address any other issues that may pop up when/if they happen

**Comment by scottx611x** [comment]
It looks like all repo updates are being doubled in Slack!

**Comment by scottx611x** [comment]
test
