### ISSUE TITLE
Display Users launched Visualizations in the UI somewhere

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2260]
Similar to how we display a User's launched `Analyses`, there should be somewhere in the UI where a `User's` launched `VisualizationTools` are shown as well.

Things to consider:
- Should the middle column on the dashboard display a merged list of `Analyses` and `Visualizations`?
- Should that column exist at all? I think we've talked before about having this information about `Analysis` and `Visualization` launches shown in the `Dataset Preview`
- A `User` should be able to click and navigate to a previously launched `VisualizationTool` if it is still running #2433
- ~~~A `User` may want to reanimate a "dead" `VisualizationTool`~~~ #2433 
- A deletion button & UI tests will be needed for items in the `VisualizationTool` listing as well
- A change like this could warrant the removal of the 2nd and 3rd columns of the dashboard which could make room for the editable markdown-based landing page that was demonstrated [here](https://github.com/scottx611x/django_dynamic_markdown_pages) ([Requires Django 1.8](https://github.com/refinery-platform/refinery-platform/issues/449))

Notes I've written earlier:
```
Tool.has_container ->Default False
Tool.is_new -> default True

Utilize these two fields to be able to reanimate Visualization Tools
```
```
VisualizationTool urls to utilize their own uuid so that we can destroy & dissassociate containers but maintain urls on relaunch of said Tools/containers
```

TODO:
- [ ] Display useful info in the ui: launch params, input files, .etc
- [x] Be able to relaunch a visualization #2433
- [x] Visualizations tab that includes a listing of visualizations that have been launched on a given dataset #2437
- [x] Tweak tools api to be able to filter on just visualiztions #2437
- [x] Track status: Running/not running etc. https://github.com/refinery-platform/refinery-platform/pull/2433
