### ISSUE TITLE
Collaboration Permissions - View Meta Data Level

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2389]
Split read permissions to full read and meta data read

- [x] update model?
- [x] update API
- [x] ~update UI dashboard share~ Separate issue
- [x] update UI file browser (hide name & download column)
- [x] ~update UI collaboration~
