### ISSUE TITLE
Satori - UI Bugs

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2673]
*Consolidates all Satori UI bugs into on big issue

- [ ] Show number of data sets related to hovered ontology term Ref #975
       The number of highlighted data sets in the current collection should be shown so that the user can quickly get an idea of how much more is there to explore.
- [ ] Double clicking on a node === rooting it Ref #973
       Double clicking on a rectangle roots it but a double click on a node in the list graph currently does nothing. The behavior should be unified.
- [ ] Query-search search message hiccup Ref #971
       Sometimes when a user queries for a term and then search, a notification is displayed below the search bar saying that nothing was found even though the correct search results are shown.
I believe there is a race condition going on somehow or the promises get mixed up.
- [ ] Treemap should feature the same node context menu of the list graph Ref #968
       Currently the treemap is a little bit limited in terms of the action, i.e. one can only zoom into a term, i.e. rooting the term, but not just querying for it. Having the same context menu is also less confusing to the user.
- [ ] Add short explanation for precision and recall Ref #966
       Add a little question mark next to the precision and recall button and open a little modal or something that gives a very brief explanation of the terms. Maybe even add a small visual explanation.
- [ ] Some annotations are not highlighted Ref #965
       Query for "native cell" and hover over the first data set (14909: Genome-wide location analysis of BMP (SMAD1) in mouse erythroid progenitors co-occupted with lineage specific regulators (GATA1, GATA2)) retrieved.Observed:Only OWL:Thing will be highlighted!Expected:At least native cell needs to be highlighted because we queried for it.Searching for the data set just by itself uncovered that only 3 out of the 6 annotations are highlighted when mousing over the item in the data set list. For example the term neuroblast (which is definitely drawn) is not being highlighted.
--
- [ ] Treemap: Add tooltip Ref #963
      A debounced tooltip should be added to the rectangles so that hidden text appears once the user hovers over a rectangle
--
- [ ] Treemap labels missing if URL has branchld=2 Ref #2494
     Labels are not drawn on the rectangles of the Treemap... though if you resize the window labels are drawn.
      * Go to issue for reference
- [ ] Node ID > URL: only first part is visible Ref #2491 
      In Satori, when you click on a node to bring up the info box, and then click on the arrow to get a url, only the first portion is visible: Typically the protocol and domain name. If I triple click it seems to select the whole string which I can then paste somewhere else. Is that sufficient? Could imagine having the url in a read only input box, for example, so you could select by dragging, instead needing to know and trust a triple click.
- [ ] In "Two Bar" mode, recall and precision overlap after sort #2489   
       For each item, the two bars now overlap in the top half of the cell, leaving the bottom half empty. (Check issue for reference)
- [ ] Found set counts not usually preserved across Satory toggles Ref #2339 
      I would expect every transition in and out of Satori to behave like the second to last one, where the found count is preserved.
And what's up with the context only showing the first time? Though I don't know whether that is good or bad.
- [ ] Search data sets + satori + title click = missized columns Ref #2338 
      The Data Sets and Workflows columns are short. The shortness is consistent, and the same on both FF and Chrome. See issue
- [ ] Minor discrepancies btwn test doc & real world Ref #2152 
       See issue.
- [ ] Missing tutorials Ref #2141 
       The tutorial just exits: maybe the links are bad, or maybe the content was never written?
- [ ] Tutorials don't work if the relevant component in Satori is minimized Ref #2140 
        See issue for images
- [ ] Context menu interferes with lock highlight propagation Ref #2138 
        Highlight even with context menu on. All parts of the UI to agree on the lock state for a node.
- [ ] Jumpy context menu if column scroll on FF Ref #2136 
       Chrome looks fine... though if the bug even matters, maybe just turn off the context menu when scrolled?
- [ ] Nodes missing from node-link after sorting while zoomed Ref #2135 
       Many nodes are missing from the node-link display, image in issue.
- [ ] Re-render truncated after zoom-out in Satori Ref #2134 
       Should see all columns, and should see all of each column, just as when you first zoom out. Issue for images
- [ ] Menu toggle up missing icon on FF Ref #2133 
        The menu toggles, but the space where there should be an up arrow is just empty now. Chrome works; this is just FF. (You can still click in that region to toggle, there's just no icon.) Issue for images
- [ ] It never loads if data sets loads first? Ref #2126 
        See issue for backstory
- [ ] "Introduction to the data set view only shown with Satori open? Ref #2124 
        The "Introduction to the Data Set View" tutorial "i" is only shown with exploring with Satori... but it actually only deals with the Data Sets column... If the tutorial is useful, perhaps it should be shown all the time?
- [ ] Adding search to satori query seems to product result, but not rendered Ref #1931 
       There shouldn't be a result for the tighter query, if there isn't one for the looser.
... but if there were, it should be displayed.
- [ ] Data Set Summary link not working Ref #1925 
```
dashboard.js:3805 Uncaught TypeError: f._start is not a function
    at Object.f.start [as satori-data-set-summary] (https://refinery-static.s3.amazonaws.com/js/dashboard.js:3:28766)
    at Object.b [as start] (https://refinery-static.s3.amazonaws.com/js/dashboard.js:4:17037)
    at HTMLDocument.f.clickHandler (https://refinery-static.s3.amazonaws.com/js/dashboard.js:4:10055)
    at HTMLLIElement.onclick (https://test.stemcellcommons.org/#/exploration?context=OWL:Thing&branchId=0&visibleDepth=1:1:1)f.start @ dashboard.js:3805b @ dashboard.js:4919f.clickHandler @ dashboard.js:4529onclick @ VM17228 exploration?context=OWL:Thing&branchId=0&visibleDepth=1:1
```
- [ ] Tutorial can be instantiated on top of prior ones Ref #1924 
       The background becomes darker and darker on each click as div.introjs-overlay pile up ontop of eachother
- [ ] Mis-sized if coming from preview with lock active Ref #1921
      Check issue
- [ ] Tree map loses lock state if window resize forces redraw  Ref #1920
      The treemap may lose it's orange state: It feels like the color may just be in the view, but is not being pulled from the underlying model on redraw.
- [ ] Lock state not mirrored btwn treemap and node list Ref #1918
      This does not unlock it in the popover, and we seem to be in an inconsistent state: The datasets on the left are still orange, but there is no orange in the treemap: Locking and unlock some other box in the tree map will cause only some of the data sets to be reset.
- [ ] "Zoom out" is really more of a zoom toggle Ref #1917
      "Zoom out" zooms out... and then back in if you click again. Perhaps it should just be "Zoom", with neither plus nor minus in the magnifying glass icon? Less work than toggling the button.
The manual testing insctuctions say:
The topbar of the node-link diagram should flip and column-specific buttons should appear.
... but I'm not sure what that means.
- [ ] Treemap depth label mispositioned in FF only Ref #1916
     Notice that the text, along with the left edge, are positioned too low.
- [ ] Popover for current screen split mode remains even after mouse leaves Ref #1915
       The first popover remains, and the new is also displayed, probably overlapping.
Move around to other parts of the screen: The popover for the current screen-split mode is not going away.
- [ ] Treemap info="i" does nothing Ref #1914
```
null:119 TypeError: Cannot set property '_noVisibleDepthNotification' of undefined
    at i (null:3)
    at Object.j.start [as satori-treemap] (null:3)
    at Object.b [as start] (null:3)
    at j.r.introStart (null:3)
    at fn (eval at compile (null:235), <anonymous>:4:275)
    at b (null:124)
    at e (null:281)
    at m.$eval (null:143)
    at m.$apply (null:146)
    at HTMLButtonElement.<anonymous> (null:281)
```
- [ ] Scroll node column down, change sort, and column does not redraw Ref #1913
      See issue
- [ ] Treemap depth controller: Click the up-arrow but the down arrow gets highlighted #1911
     The depth is not updated (#1909), and The down-arrow part of the controller is highlighted momentarily
- [ ] Treemap depth controller treats click as mousedown FF only Ref #1910
       Instead of incrementing just by one, it will continue until it maxes out. (Actually, it looks like it overshoots, and then is reset.)
Click the down arrow, without holding it down, and the same thing: It will go down to -1, actually, and then set back to 1.
- [ ] Treemap depth controller requires mouse movement Chrome only Ref #1909
       The arrow is highlighted (Actually, the lower half of the arrow: #1911), but nothing else happens.
- [ ] Treemap labels not being cleaned up on redraw Ref #1908
______________________________________
- [ ] Treemap loses orange Ref #2132 
```
Error: this.children[(this.visibleDepth + 1)] is undefined
i.prototype.removeLevelsOfNodes@https://refinery-static.s3.amazonaws.com/js/commons.js:4:15246
i.prototype.adjustLevelDepth@https://refinery-static.s3.amazonaws.com/js/commons.js:4:9854
set/<@https://refinery-static.s3.amazonaws.com/js/commons.js:4:20883
f/q<@https://refinery-static.s3.amazonaws.com/vendor/angular/angular.min.js:160:50
e@https://refinery-static.s3.amazonaws.com/vendor/angular/angular.min.js:45:485
og/k.defer/c<@https://refinery-static.s3.amazonaws.com/vendor/angular/angular.min.js:48:414
```
- [ ] Icon loading could be enhanced Ref #1905
       Check issue for more comments
- [ ] Ontology info box mispositioned on FF only #1403

- * Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Version of the web browser and OS: ff macos
* Environment where the error occurred: test production

### Steps to reproduce
Following the test protocol:
>**4. Click on the rectangle once.**
> In addition to the description above everything should be highlighted in orange. Also, the clicked rectangle should display a subtle lock icon.
> **5. Move mouse cursor elsewhere.**
> Data sets, nodes, and rectangles should still be highlighted in orange but the black outlines / highlights should be gone.

In particular:
- After locking a rectangle in the tree map, move the mouse over any portion of the data sets list on the left, (much of the map will turn orange), and then move the mouse out of that region. (No clicking.)

### Observed behavior
On mouse-leave from the datasets list, the locked rectangle looses its orange

### Expected behavior
It still should be orange? (More generally, if a treemap box is locked, it should be orange, right?)

![screen shot 2017-09-13 at 11 09 09 am](https://user-images.githubusercontent.com/730388/30384911-9048853e-9873-11e7-8bfd-4df19990eefc.png)

_____________________________

**Comment by jkmarx** [comment]
With v1.6.9 Explore/Satori has been removed.
