### ISSUE TITLE
Explore Data-Set Cart

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2674]
Consolidates all the data-set cart related issue. The data cart is closely coupled with Satori. The cart itself may be unused by the new dashboard.

- [ ] Inconsistent state if query cleared while data cart still open Ref #1904
- [ ] Add all to data cart does not do anything Ref #1552 
- [ ] First add-all-to-cart takes 4 seconds with 119 data sets Ref #2129 
- [ ] Data cart sizing inconsistent btwn FF/Chrome Ref #2128 - [ ]

**Comment by jkmarx** [comment]
With v1.6.9 Explore/Satori has been removed.
