### ISSUE TITLE
Metadata/Data File Editing for Existing DataSets

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2700]
Its a common use case for users to be able to edit errors in their metadata, and upload and associate new data files or replace existing data files after a successful metadata upload.

HSCI Scenarios:

- 1: An analyst uploads an ISA archive and corresponding data files but needs to correct an error in metadata
  - Conditions:
    - No files can be added or removed. Only typographical errors or errors in the content of the metadata are allowed to be edited.
    - Only ISATabs will be supported in this iteration. Tabular metadata upload requires some extra user intervention i.e. selection of `Data File Column`.
    - No `Analyses` or `Visualizations` can be performed on the DataSet
    - Data files uploaded before the edits have been made will be reassociated with the new `DataSet`

- 2: An analyst successfully uploads an ISA archive but needs to add some data files later
  - Functionality will be added to the File Browser to be able to upload and associate files with existing `Nodes` as well as provide a valid url to a data file.
    - This will potentially mean overwriting/purging existing data files so we should be wary of that
  - This functionality will exist for all `DataSets` regardless if they are ISATab or Tabular

### ToDos:
- Frontend
  - [x] Button to `Update DataSet` in the FileBrowser dependent on aforementioned conditions
  - ~~~[ ] Modal to allow selection of new ISATab metadatafile~~~ Redirects to import pages now
  - [x] Extend File Browser code to be able to upload and associate new data files with existing `Nodes`
- Backend
  - [x] Extend API endpoints for `DataSet` update
    - [x] DataSets should be able to report on their "cleanliness"  Ref: #2784
    - ~~~[ ] Check that newly referenced data files are a 1::1 match with what existed prior~~~ We ended up vetoing this and allowing removal and addition of datafiles during a metadata revision
    - [x] Reassociate data files with updated `DataSet` if referenced in new metadata
    - [x] `DataSet` version should be incremented

Add/remove/replace data files for any existing data set that `is_clean`

**Comment by scottx611x** [comment]
Speeding up ISA-Tab import performance could alleviate the need to run some background tasks for upload.

**Comment by scottx611x** [comment]
Are Nodes mutable?
If so, how does this affect DataSet versioning? i.e. if I edit a Node's meta data/(replace/remove/add) a datafile/add a new Node what does the resulting provenance graph structure look like, and what does this do to a DataSet's version?

**Comment by scottx611x** [comment]
- [ ] Be able to navigate to metadata import pages from `DataSet` details page: `/data_sets/<dataset_uuid>/#/about/` for both ISATab and Tabular `DataSets`
  -  [ ] Add button/link to `refinery/ui/source/js/data-set-about/partials/details.html`
    - `User` must own said DataSet
    - `DataSet` must be clean (`DataSet.is_clean()`)
  -  [ ] Navigate to different urls with url param: `?dataSetUUID=<data_set_uuid>` for ISATab/Tabular:
    - ISATab: `/data_set_manager/import/#/isa-tab-import?dataSetUUID=<data_set_uuid>`
    - Tabular: `/data_set_manager/import/#/?dataSetUUID=<data_set_uuid>`
- [ ] Update respective Controllers/Directives/Partials to show/hide ui components if the metadata upload is a new metadata revision-based one
  - `scope.dataSetUUID = $location.search().dataSetUUID;`
  - `scope.isMetaDataRevision = !!scope.dataSetUUID;`
  - ISATab:
    - `ui/source/js/data-set-import/controllers/isa-tab-import.js`
    - `ui/source/js/data-set-import/directives/isa-tab-import.js`
    - `ui/source/js/data-set-import/partials/isa-tab-import.js`
  - Tabular:
    - `ui/source/js/data-set-import/controllers/meta-data-table.js`
    - `ui/source/js/data-set-import/directives/metadata-table.js`
    - `ui/source/js/data-set-import/partials/metadata-table.js`
  - [ ] The functionality to `check datafiles` will need to be updated to look at datafiles that this `DataSet` has associated rather than only what's in the upload area
  - [ ] We should warn users if we are going to remove any existing datafiles
  - [ ] Find out which components will be shown/hidden

- [ ] Update Services that import said metadata files to know that an import could be a metadata revision only one
  - ISATab: `ui/source/js/data-set-import/services/isa-tab-import-api.js`: `/data_set_manager/import/isa-tab-form/`
  - Tabular: `ui/source/js/data-set-import/services/tabular-file-import-api.js`: `/data_set_manager/import/metadata-table-form/`

- [ ] Update corresponding backend components to check for the constraints within [#2700](https://github.com/refinery-platform/refinery-platform/issues/2700):
  - ISATab: `data_set_manager.views.ProcessISATabView`
  - Tabular: `data_set_manager.views.ProcessMetadataTableView`
  - No files can be added or removed. Only typographical errors or errors in the content of the metadata are allowed to be edited.
  - Datafiles that have already been uploaded will be re-associated
  - The changes here should be run within an atomic db transaction so that if anything fails, we don't write any new state to the DB, and the old DataSet is still accessible
  - 3 scenarios regarding data files:
    - No data files uploaded: we'll just import the new metadata file and not worry about much
    - Some data files have been uploaded and are referenced in the revised metadata file: have to check if the data files uploaded prior match up with whats referenced in the new meta data
    - Some data files have been uploaded and some/None of them are referenced in the new metadata file: we have to warn users about what will be deleted See `2.` above

### General Notes:
- ISATabs can be imported by file or url. There are some splits in the codebase based on this
- Only `DataSet` owners are allowed to revise the metadata, this should be taken into consideration with the latest changes regarding changing DataSet ownership
- Do we invalidate prior Nodes etc. ? Or do we just increment the DataSet version and forge ahead?
