### ISSUE TITLE
Master issue for UI overflow

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2968]
Consolidating bugs relating to overflow in the UI. There might be CSS fixes to make divs scrollable, or there might be layout changes, so we don't get stuck trying to fit too much on the screen. Will add to this list as appropriate.

- [ ] Dashboard data sets with narrow window
<img width="249" alt="screen shot 2018-08-29 at 10 48 11 am" src="https://user-images.githubusercontent.com/730388/44805497-63a2f900-ab92-11e8-9e72-bf93e8c9d714.png">

- [ ] File display selector (was  #1901)
<img width="249" src="https://user-images.githubusercontent.com/730388/28084826-e0b55d98-6647-11e7-9d3f-96f89d90924c.png">

- [ ] File browser sidebar (was #2364)
<img width="249" src="https://user-images.githubusercontent.com/730388/32734561-662e96ae-c860-11e7-9a06-ef68df6dd636.png">

- [ ] Multiple vis launches  (was #2766)
<img width="249" src="https://user-images.githubusercontent.com/730388/40016889-c1ccf97e-5785-11e8-88f6-09db61d5feca.png">
