### ISSUE TITLE
Meta-data update - modify existing node's content - UI

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2982]
- Modify existing cell in file browser (UI)
    - [x] UI Grid implemented
    - [x] Basic Text Edit a cell with Double Click (utilizing the library)
    - [ ] Add ui validation

**Comment by scottx611x** [comment]
https://github.com/refinery-platform/refinery-platform/issues/2896 Will come into play. We may not want to allow for such an edit to happen if a given `Node` and any of it's parent/descendants were used as Tool inputs
